language: objective-c
xcode_project: AP Physics Tools/AP Physics Tools.xcodeproj # path to your xcodeproj folder
xcode_scheme: AP Physics Tools
osx_image: xcode9

script: xcodebuild clean && xcodebuild build -sdk iphonesimulator10.1 -project AP\ Physics\ Tools/AP\ Physics\ Tools.xcodeproj -scheme AP\ Physics\ Tools  CODE_SIGNING_REQUIRED=NO